#!/usr/bin/env Rscript
# 60_fig4_missing_panels.R
# Generate missing Fig4 panels: outgoing chords + L-R dotplot
library(CellChat); library(dplyr); library(ggplot2)
library(ComplexHeatmap); library(grid)

cellchat <- readRDS("results/cellchat_ucsf_mid.rds")

all_cols <- c(
  "CD14_M"="#66C2A5","CD16_M"="#DA9870","dNK"="#BE979C","EVT"="#AB98C8",
  "FB"="#99D594","fEC"="#FC8D59","HB"="#D73027","SCT"="#4575B4",
  "VCT"="#91BFDB","vEC"="#B3B3B3"
)

# ============================================================
# 1. Outgoing chord diagrams: HB → vEC / CD14_M / dNK
# ============================================================
for(target in c("vEC","CD14_M","dNK")) {
  fname <- sprintf("figures/Fig4/Fig4_cellchat_chord_HB_%s.png", target)
  png(fname, w=16, h=14, units="in", res=300)
  par(mar=c(1, 1, 3, 4))
  
  netVisual_chord_gene(cellchat, sources.use="HB", targets.use=target,
    title.name=NULL,
    lab.cex=1.2, small.gap=2, big.gap=15,
    color.use=all_cols,
    show.legend=FALSE)
  title(sprintf("HB \u2192 %s", target), cex.main=2.5)
  
  lgd <- Legend(
    at = c("HB", target),
    type = "grid",
    legend_gp = gpar(fill = c(all_cols["HB"], all_cols[target])),
    title = "Cell State",
    title_gp = gpar(fontsize = 18, fontface = "bold"),
    labels_gp = gpar(fontsize = 16),
    grid_width = unit(8, "mm"),
    grid_height = unit(8, "mm")
  )
  draw(lgd, x = unit(1, "npc") - unit(5, "mm"),
       y = unit(0.55, "npc"), just = c("right", "center"))
  
  dev.off()
  cat(sprintf("Saved %s\n", fname))
}

# ============================================================
# 2. Combined chord panel: vEC+fEC → HB side-by-side
# ============================================================
library(png)
for(src in c("vEC","fEC")) {
  infile  <- sprintf("figures/Fig4/Fig4_cellchat_chord_HB_%s.png", src)
  outfile <- sprintf("figures/Fig4/Fig4_cellchat_chord_HB_%s_v2.png", src)
  # Already generated by 53_chord_right.R, reuse
  if(file.exists(infile)) {
    cat(sprintf("  Reusing %s\n", infile))
  }
}

# ============================================================
# 3. Key L-R gene-pair dotplot (top pairs by probability)
# ============================================================
inc_raw <- subsetCommunication(cellchat, targets.use="HB")
out_raw <- subsetCommunication(cellchat, sources.use="HB")

ct_levels <- c("CD14_M","dNK","FB","fEC","SCT","VCT","vEC")

# Incoming: top pairs from major sources
hb_inc_top <- inc_raw %>%
  filter(source %in% c("FB","vEC","fEC")) %>%
  arrange(desc(prob)) %>%
  head(30) %>%
  mutate(pair = paste0(ligand," \u2192 ",receptor),
         direction = "Incoming \u2192 HB",
         source_label = source)

# Outgoing: top pairs to major targets
hb_out_top <- out_raw %>%
  filter(target %in% c("vEC","CD14_M","dNK")) %>%
  arrange(desc(prob)) %>%
  head(20) %>%
  mutate(pair = paste0(ligand," \u2192 ",receptor),
         direction = "Outgoing \u2190 HB",
         source_label = target)

all_top <- bind_rows(hb_inc_top, hb_out_top) %>%
  mutate(direction = factor(direction, levels=c("Incoming \u2192 HB","Outgoing \u2190 HB")))

# Pathway colors — use functional category mapping
path_cat <- c(
  "COLLAGEN"="#4575B4","FN1"="#D73027","TGFb"="#FDAE61",
  "SPP1"="#7B4FA0","LAMININ"="#2D8B57","PTPRM"="grey60",
  "CD45"="grey50","GDF"="grey70","NOTCH"="grey70",
  "BMP"="grey70","PECAM1"="#1B6B93","THBS"="#C62828",
  "IGF"="#E31A1C","PDGF"="#FB9A29","MHC-I"="#33A02C",
  "CD99"="#6A3D9A","SEMA3"="#B15928","APP"="grey70"
)

p_dot <- ggplot(all_top, aes(x=source_label, y=reorder(pair, prob),
                              size=prob, fill=pathway_name)) +
  geom_point(shape=21, colour="grey30", stroke=0.3) +
  facet_grid(direction ~ ., scales="free_y", space="free_y", switch="y") +
  scale_size_continuous(range=c(2.5, 8), name="Comm. probability") +
  scale_fill_manual(values=path_cat, name="Pathway") +
  theme_bw(base_size=11) +
  theme(
    axis.text.y=element_text(size=8.5, face="bold", color="black"),
    axis.text.x=element_text(size=10, face="bold", color="black"),
    axis.title=element_blank(),
    panel.grid.major=element_line(colour="grey92"),
    panel.grid.minor=element_blank(),
    strip.background=element_rect(fill="grey95"),
    strip.text=element_text(size=11, face="bold", color="black"),
    legend.position="right",
    legend.box="vertical",
    legend.title=element_text(color="black"),
    legend.text=element_text(color="black"),
    plot.title=element_text(face="bold", size=13, hjust=0.5, color="black"),
    plot.subtitle=element_text(color="black")
  ) +
  guides(fill=guide_legend(ncol=2, override.aes=list(size=3)),
         size=guide_legend(override.aes=list(fill="grey50"))) +
  labs(title="Key ligand-receptor pairs with Hofbauer cells",
       subtitle="Top interactions by communication probability | FB/vEC/fEC \u2192 HB  &  HB \u2192 vEC/CD14_M/dNK")

ggsave("figures/Fig4/Fig4F_cellchat_dotplot_key_pairs.png",
  p_dot, width=10, height=8.5, dpi=300, bg="white")

cat("Saved Fig4_cellchat_dotplot_key_pairs.png\n")

# ============================================================
# 4. Compact outgoing bubble for supplement
# ============================================================
png("figures/Fig4/Fig4_cellchat_bubble_outgoing_supp.png",
    w=8, h=7, units="in", res=300)
netVisual_bubble(cellchat,
  sources.use="HB",
  targets.use=c("vEC","CD14_M","dNK","fEC","FB","VCT","SCT"),
  remove.isolate=FALSE,
  title.name="HB \u2192 target cells")
dev.off()
cat("Saved Fig4_cellchat_bubble_outgoing_supp.png\n")

cat("\n=== All missing panels done ===\n")
